//AUTH
export const AUTH_USER = 'AUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const SIGNUP = 'SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const VERIFICATION_MAIL_SENT = 'VERIFICATION_MAIL_SENT';
export const VERIFICATION_MAIL_SENT_FAILURE = 'VERIFICATION_MAIL_SENT_FAILURE';
export const OTP_SENT = 'OTP_SENT';
export const SHOW_FORGOT_PASSWORD = 'SHOW_FORGOT_PASSWORD';
export const PASSWORD_UPDATE_SUCCESS = 'PASSWORD_UPDATE_SUCCESS';
export const PASSWORD_UPDATE_ERROR = 'PASSWORD_UPDATE_ERROR';
export const RETRIEVE_PASSWORD = 'RETRIEVE_PASSWORD';

export const SUBMIT_EMAIL_FOR_FORGOT_PASSWORD_SUCCESS = 'SUBMIT_EMAIL_FOR_FORGOT_PASSWORD_SUCCESS';
export const SUBMIT_EMAIL_FOR_FORGOT_PASSWORD_FAILRUE = 'SUBMIT_EMAIL_FOR_FORGOT_PASSWORD_FAILRUE';

export const BARS_SUCCESSFULL = 'BARS_SUCCESSFULL';
export const BARS_NOT_SUCCESSFULL = 'BARS_NOT_SUCCESSFULL';


// This project specific
export const CLAIM_ADDITION_SUCCESS = 'CLAIM_ADDITION_SUCCESS';
export const CLAIM_ADDITION_FAILURE = 'CLAIM_ADDITION_FAILURE';
export const CHANGE_URL = 'CHANGE_URL';
export const SELECTED_TAB = 'SELECTED_TAB';

export const VIEW_CLAIM_RESPONSE_SUCCESS = 'VIEW_CLAIM_RESPONSE_SUCCESS';
export const VIEW_CLAIM_RESPONSE_FAILURE = 'VIEW_CLAIM_RESPONSE_FAILURE';
export const CLEAR_URL = 'CLEAR_URL';

export const PNR_DETAILS_SUCCESS = 'PNR_DETAILS_SUCCESS';
export const PNR_DETAILS_FAILURE = 'PNR_DETAILS_FAILURE';

export const UPLOAD_FAILURE_BOARDING_PASS = 'UPLOAD_FAILURE_BOARDING_PASS';
export const UPLOAD_SUCCESS_BOARDING_PASS = 'UPLOAD_SUCCESS_BOARDING_PASS';


export const UPLOAD_SUCCESS_ITEM_IMAGES = 'UPLOAD_SUCCESS_ITEM_IMAGES';
export const UPLOAD_FAILURE_ITEM_IMAGES = 'UPLOAD_FAILURE_ITEM_IMAGES';

export const CLEAN_UPLOAD_URLS = 'CLEAN_UPLOAD_URLS';

export const RECORDED_SUCCESS = 'RECORDED_SUCCESS';
export const RECORDED_FAILURE = 'RECORDED__FAILURE';

export const FETCH_CLAIM_SUCCESS = 'FETCH_CLAIM_SUCCESS';
export const FETCH_CLAIM_FAILURE = 'FETCH_CLAIM_FAILURE';

export const GOTO_DASHBOARD = 'GOTO_DASHBOARD';

export const RECORDED_ITEM = 'RECORDED_ITEM';

export const RECORD_ITEM_SUBMITTED_SUCCESS = 'RECORD_ITEM_SUBMITTED_SUCCESS';
export const RECORD_ITEM_SUBMITTED_FAILURE = 'RECORD_ITEM_SUBMITTED_FAILURE';

export const FETCH_AIRPORTS_SUCCESS = 'FETCH_AIRPORTS_SUCCESS';
export const FETCH_AIRPORTS_FAILURE = 'FETCH_AIRPORTS_FAILURE';

export const LOST_ITEM_LOCATION_SUCCESS = 'LOST_ITEM_LOCATION_SUCCESS';
export const LOST_ITEM_LOCATION_FAILURE = 'LOST_ITEM_LOCATION_FAILURE';

export const RECORD_ITEM_LOST_UPLOAD_SUCCESS = 'RECORD_ITEM_LOST_UPLOAD_SUCCESS';
export const RECORD_ITEM_LOST_UPLOAD_FAILURE = 'RECORD_ITEM_LOST_UPLOAD_FAILURE';

export const ITEM_ADDITION_SUCCESS = 'ITEM_ADDITION_SUCCESS';
export const ITEM_ADDITION_FAILURE = 'ITEM_ADDITION_FAILURE';

export const SEARCH_DASHBOARD = 'SEARCH_DASHBOARD';

export const ITEM_FOUND_IN_LOCKER_SUCCESS = 'ITEM_FOUND_IN_LOCKER_SUCCESS';
export const ITEM_FOUND_IN_LOCKER_FAILURE = 'ITEM_FOUND_IN_LOCKER_FAILURE';

export const USERS_FETCH_SUCCESS = 'USERS_FETCH_SUCCESS';
export const USERS_FETCH_FAILURE = 'USERS_FETCH_FAILURE';

export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_FAILURE = 'ADD_USER_FAILURE';

export const ROLES_FETCH_SUCCESS = 'ROLES_FETCH_SUCCESS';
export const ROLES_FETCH_FAILURE = 'ROLES_FETCH_FAILURE';

export const REGIONS_FETCH_SUCCESS = 'REGIONS_FETCH_SUCCESS';
export const REGIONS_FETCH_FAILURE = 'REGIONS_FETCH_FAILURE';

export const ADD_REGIONS_SUCCESS = 'ADD_REGIONS_SUCCESS';
export const ADD_REGIONS_FAILURE = 'ADD_REGIONS_FAILURE';

export const STATIONS_FETCH_SUCCESS = 'STATIONS_FETCH_SUCCESS';
export const STATIONS_FETCH_FAILURE = 'STATIONS_FETCH_FAILURE';

export const ADD_STATIONS_SUCCESS = 'ADD_STATIONS_SUCCESS';
export const ADD_STATIONS_FAILURE = 'ADD_STATIONS_FAILURE';

export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const CLOSE_ERROR_DIALOG = 'CLOSE_ERROR_DIALOG';
export const OPEN_ERROR_DIALOG = 'OPEN_ERROR_DIALOG';
